linkall appears to be working

diff --git a/dotphile b/dotphile
--- a/dotphile
+++ b/dotphile
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+command -v stow >/dev/null 2>&1 || { echo >&2 "GNU stow is not installed.  Aborting."; exit 1; }
+
 add()
 {
   package=$1
@@ -14,12 +16,12 @@ add()
 
 link()
 {
-  stow $1 -d ~/dotfiles
+  echo stow $1 -d ~/dotfiles
 }
 
 linkall()
 {
-  find . -maxdepth 1 -mindepth 1 -type d -printf '%f\n' |\
+  find ~/dotfiles -maxdepth 1 -mindepth 1 -type d -printf '%f\n' |\
     egrep -v '^\..*$' |\
     xargs -I {} stow {} -d ~/dotfiles
 }
@@ -27,24 +29,29 @@ linkall()
 args=`getopt la: $*`
 if [ $? -ne 0 ]
 then
-  echo ’Usage: ...’
+  echo "Usage: ..."
   exit 2
 fi
+
+if [ ! -d ~/dotfiles ]; then
+  git clone git@github.com:pklingem/dotfiles ~/dotfiles
+fi
+
 set -- $args
 
 for i
 do
   case "$i"
   in
+    -l|--link)
+      linkall
+
+      shift;;
     -a|--add)
       package="$2"; shift; config="$3"; shift;
 
       add $package $config
       echo link $package
-
-      shift;;
-    -l|--link)
-      linkall
 
       shift;;
     --)
